### ISSUE TITLE
Feature Request - Support having more than one library and circulation desk with a single instance

### ISSUE THREAD

**Issue by jeffnm** [wc-library/selfcheck#11]
Can we add support for serving different libraries and desk? We don't want to expose that to the clients, but on the server side it would be nice to allow multiple locations to be served by the single instance. 

IP address restrictions probably need to still be handled by Apache's reverse proxy, but not having to set up multiple instances would be nice.

**Comment by jeffnm** [comment]
As part of this enhancement, it would be good to have a way to indicate the location in the client. Either a logo switch or perhaps just a text variant.

**Comment by jcuenod** [comment]
This is implemented in the new branch
