### ISSUE TITLE
Tailwind UI not loading behind Apache Proxy

### ISSUE THREAD

**Issue by jeffnm** [wc-library/selfcheck#17]
@jcuenod 

I attempted a test deployment of your Tailwind UI rewrite, and I'm getting the following error. 

`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

I can give you the full trace if you want it. 

It's running behind an Apache reverse proxy still that is limiting access to specific IPs and I did add that IP to the `config.js`, so I see "Loading" in the browser, but it's not getting past that.

**Comment by jcuenod** [comment]
Hmm, hard to know why that's happening but my initial guess is that it's because this function: https://github.com/jcuenod/selfcheck/blob/tailwind-react-ui/main.js#L53-L73 was not using `return` so when failing, it would try to call `res.json()` more than once. Latest commit should resolve.

**Comment by jeffnm** [comment]
Well, you solved the error on the server, but I'm still only seeing "Loading" in the browser.

**Comment by jcuenod** [comment]
This must be an issue with figuring out the IP address of the client. I'll have a go with it later this afternoon.

**Comment by jeffnm** [comment]
I think we figured out most of the issues. Can you make a PR with this code against a fresh branch on this Repo? Let me know if I need to make the target branch for you.

**Comment by jcuenod** [comment]
The one thing is still that image but yes...

**Comment by jcuenod** [comment]
It seems that I don't have the requisite permissions to push to `wc-library` (which means I can't create a branch for a PR either)

**Comment by jeffnm** [comment]
Access issue was resolved, along with other items in this Issue.

**Comment by misilot** [comment]
@jeffnm how did you solve this?

We are looking to build this into a container.

**Comment by jeffnm** [comment]
@misilot I think it was a combination of code changes (which should be present in the master branch) and the apache config for the reverse proxy. 

something like:
```
        RequestHeader set X-Forwarded-Proto "https"
        ProxyPreserveHost On
        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/
```

It's working on our server currently, but we aren't using containers. Are you getting an error? Have you added the IP address for the client to the `config.js`?

**Comment by misilot** [comment]
I've tried adding 0.0.0.0 since I won't know what the container IP is but
that doesn't seem to work.

I'll keep poking at it.

**Comment by jcuenod** [comment]
Try `docker inspect <container-name>` I think if you pipe that through `| grep ip` you should be able to find the IP address.

But you may want to just bind the port with `-p 3000:3000` (that will make it available at localhost).

Sorry, these comments are untested -- just flying by the seat of my pants here. I hope it's helpful...

**Comment by misilot** [comment]
Yea, but it’s not something I can guarantee will survive reboots with multiple images running. I think I can do it if throw Apache in front of it instead of trying to access from my local computer. On Jul 25, 2024, at 4:38 PM, James Cuénod ***@***.***> wrote:﻿
Try docker inspect <container-name> I think if you pipe that through | grep ip you should be able to find the IP address.

**Comment by jcuenod** [comment]
Sorry, I edited my initial reply to mention binding the port. If you bind the port, it should be accessible on localhost (and then it's just a matter of telling your firewall to allow network traffic over that port).
