### ISSUE TITLE
Code audit

### ISSUE THREAD

**Issue by jeffnm** [wc-library/selfcheck#8]
Review the code for any security issues and any areas that should be refactored.

**Comment by jcuenod** [comment]
Note, this is not tested but I think you could use `express.static` to remove some redundant code: https://github.com/jcuenod/selfcheck/commit/44b77d2c693310b257cae1499212516524343b06 (I can make a PR for this).

Some other things I'm thinking:

 - Remove an index file and serve a unified one statically. I think the touch/no-touch solution can be to get the client to query the server and "untouchify" itself if the kiosk is for no-touch. So maybe an endpoint like `/isTouch` that returns true or false (it only needs to be hit onload)? Then we can remove the one index file and remove the lines dedicated to figuring out which one to serve.
 - Sanitization might be worthwhile (if you care). I'm thinking of places like https://github.com/wc-library/selfcheck/blob/master/main.js#L134
 - The client js could use some autoindent :)

**Comment by jeffnm** [comment]
These are good ideas. Including two html files was a last minute kludge when I realized we needed a touch free variant, but didn't want to throw away the keyboard prompts entirely since other locations may still want to have that as an option.

For the autoindent, should we have an `.editorconfig` for this project to maintain standard settings going forward? 

Go ahead and make a branch(es) for your work with PRs when they are ready for review and testing. Thanks!

**Comment by jcuenod** [comment]
Okay, I've done 3hrs+ at this point but I'm not able to test code (because I don't have api keys etc.)

The changes are on master at https://github.com/jcuenod/selfcheck/

I can test if you can give me testing api keys. Ripping out jquery might have been better left off for a while but I got too excited (so the fetches probably don't work)...

**Comment by jcuenod** [comment]
Also, I'm confused by https://github.com/jcuenod/selfcheck/blob/1da345df42b7777bb00a5bbedb1248834c039e35/client/js/self-check.js#L138-139

This was a `$.ajax` request using `POST` as a method but then use GET parameters...

**Comment by jeffnm** [comment]
> Also, I'm confused by https://github.com/jcuenod/selfcheck/blob/1da345df42b7777bb00a5bbedb1248834c039e35/client/js/self-check.js#L138-139
> 
> This was a `$.ajax` request using `POST` as a method but then use GET parameters...

Feel free to change that, but the route that is handling it is here if you want to see how it's working. 
https://github.com/jcuenod/selfcheck/blob/1da345df42b7777bb00a5bbedb1248834c039e35/main.js#L28

It might be a good idea to pass all of that data in the POST body data rather than in the query and parameters. I think I was trying to use POST because of the REST API concept that POST is for creating things (e.g. [one](https://www.restapitutorial.com/lessons/httpmethods.html) and [two](https://restfulapi.net/http-methods/)), and this is a loan creation. It was just easier to keep the barcode in the query (and the user id in the parameters).
